spring.application.name=Restaurant Management System

server.port=8080

spring.datasource.url=jdbc:${DB_Url}
spring.datasource.username=${DB_Username}
spring.datasource.password=${DB_Password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.user.name=${Security_User}
spring.security.user.password=${Security_Password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
